services:
  pic-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./pic:/pic
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=postgres
      - DB_PASS=Ivan100903

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.9-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ivan100903

